name: Test flow

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup build environment
      run: cp test.env .env

    - name: Build Docker image
      run: docker build -t atm-blue-node:test .

    - name: Run tests in container
      id: test
      run: |
        docker run --rm \
          atm-blue-node:test \
          sh -c "yarn install --dev && yarn test"
      continue-on-error: true

    - name: Fail job if tests failed
      if: steps.test.outcome == 'failure'
      run: exit 1